### ISSUE TITLE
network/http - Allow to make http detectors less sensitive

### ISSUE THREAD

**Issue by jmapro** [claranet/terraform-signalfx-detectors#146]
On http webchecks, alerts triggers too fast and creates false positives.

I think we should use lasting() + variables to customize the duration before triggering an alert.

**Comment by xp-1000** [comment]
removing bug label @jmapro . in my opinion this is not false positive if the site does not respond even once this is a real problem. you can still want to ignore this and make the default behavior more tolerant but this your choice, not a bug
