### ISSUE TITLE
filter-tags variables should only split first ":"

### ISSUE THREAD

**Issue by maxenced** [claranet/terraform-signalfx-detectors#186]
as per https://github.com/claranet/terraform-signalfx-detectors/blob/master/common/filter-tags/locals.tf#L14 , filter-tags variables replace every instance of `:` with `', '`. This breaks filters with more than one `:`, for ex in http detector (with filters like `url:http://github.com`

**Comment by Shr3ps** [comment]
yeah, a regex should be passed to replace() to handle this correctly
