### ISSUE TITLE
Makefile and script improvements

### ISSUE THREAD

**Issue by Shr3ps** [claranet/terraform-signalfx-detectors#203]
- target gen has inverted dependencies: should trigger "detectors" first and then "outputs"
- Yaml generation: it would be nice to have a new attribute in rule section named "unit" to allow us to suffix the detector rule description. For example: 
```
description           = "is too high > ${var.throttled_requests_threshold_major}%"
```
some classical unit suffixes: %, GB, s (or seconds), etc.
- target make module: it should also create the conf/ directory with the default Yaml for README extras.
- a new Makefile target to contribute would be nice:
  - taking as unique argument the name of a module directory
  - trigger every commands to generate what's necessary for CI validation only in this module directory: make detectors, outputs, doc

**Comment by xp-1000** [comment]
related to https://github.com/claranet/terraform-signalfx-detectors/issues/107 for the unit part (to in same times)

**Comment by xp-1000** [comment]
> Yaml generation: it would be nice to have a new attribute in rule section named "unit" to allow us to suffix the detector rule description. For example:

fixed in https://github.com/claranet/terraform-signalfx-detectors/issues/207 and https://github.com/claranet/terraform-signalfx-detectors/issues/107
