### ISSUE TITLE
Cloud Azure - Storage detectors

### ISSUE THREAD

**Issue by BzSpi** [claranet/terraform-signalfx-detectors#206]
Rework Azure Storage Account detectors to replace those in the stable branch.

Proposal: 6 new modules
* general storage account with Azure limits
* blob storage
* queue storage
* table storage
* file standard
* file premium (due to different behavior)

Claranet reference: AZ-394

**Comment by Shr3ps** [comment]
Can we re-open this? or maybe new issue for unmerged missing detectors?
