### ISSUE TITLE
[BUG] All detectors `tags` field is not working

### ISSUE THREAD

**Issue by chungktran** [claranet/terraform-signalfx-detectors#301]
**Describe the bug**
The new `tags` field in the detectors for version `v1.7.0` are not getting applied to SignalFx and always show up as new changes when doing `terraform plan` or `terraform apply`. I'm using the latest `6.7.5` version of the `splunk-terraform/signalfx` provider but still having same issue. After applying the terraform code I checked Splunk's `/detector/DETECTOR-ID` and saw that the `tags` field is still empty.

![image](https://user-images.githubusercontent.com/49414458/124622164-deafb200-de48-11eb-8dac-501ef33ef856.png)

**To Reproduce**
1. Use `claranet/terraform-signalfx-detectors//modules/somemodule?ref=v1.7.0`
2. Do `terraform apply`
3. Do `terraform plan` and see that the tags are still showing as pending changes

**Expected behavior**
The detectors' tags should be applied to SignalFx's API and should not show up as pending changes on next terraform `plan` or `apply`.

**Additional context**
I think the problem is with SignalFx's API or provider binary. After examining the provider's [detector](https://registry.terraform.io/providers/splunk-terraform/signalfx/latest/docs/resources/detector) resource I don't see anything wrong with the terraform code. However, I suggest make `tags` field optional in the terraform code.

**Comment by xp-1000** [comment]
Hello @chungktran 

you are right, tags are never applied by the signalfx provider.
I opened a PR to fix this https://github.com/splunk-terraform/terraform-provider-signalfx/pull/306

I still wait Signalfx to merge this but if it takes too much time I will probably have to remove this feature.

**Comment by xp-1000** [comment]
The issue https://github.com/splunk-terraform/terraform-provider-signalfx/issues/304 has been closed and the underlying PR merged.

I will update the provider version requirement in this repo as soon as there is a release from the provider.

**Comment by xp-1000** [comment]
https://github.com/claranet/terraform-signalfx-detectors/releases/tag/v1.9.1 fixes this !
