### ISSUE TITLE
dev: pyspelling: No such file or directory

### ISSUE THREAD

**Issue by tchernomax** [claranet/terraform-signalfx-detectors#313]
Inside the development container :
```
[root@76d8100f7e27 work]# make check-spell
pyspelling -c .spellcheck.yaml
make: pyspelling: No such file or directory
make: *** [Makefile:70: check-spell] Error 127
```

**Comment by xp-1000** [comment]
fixed by https://github.com/claranet/dockerfiles/commit/951202c1db26e4b73868010d2efaa0eac31f347d#diff-94dc3ea57721d541aae09b7bf2368c1e20d4c89996ff6df4349d86048877c0e7
