### ISSUE TITLE
[BUG] Wrong code for "stopping" aws instance state

### ISSUE THREAD

**Issue by jcneiss** [claranet/terraform-signalfx-detectors#424]
**Describe the bug**
In the local `not_running_vm_filters_aws` (https://github.com/claranet/terraform-signalfx-detectors/blob/master/common/module/locals.tf#L4), the code for "stopping" state must be 64, intead of 62, according to  the documentation (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_InstanceState.html).

**Comment by pdecat** [comment]
Hi @jcneiss, indeed! Would you care submitting a PR to fix this?

**Comment by jcneiss** [comment]
Yes i'm doing a PR

**Comment by pdecat** [comment]
Released in https://github.com/claranet/terraform-signalfx-detectors/releases/tag/v1.17.1
