### ISSUE TITLE
Drop usage of j2 for generating terraform files

### ISSUE THREAD

**Issue by pdecat** [claranet/terraform-signalfx-detectors#427]
j2 is obsolete:
* last release v1.2.1 dates from Aug 13, 2011
* python 2 only

https://pypi.org/project/j2/

**Comment by rsicart** [comment]
Perhaps we could replace it by j2cli, which seems more up to date and python3 compatible: https://github.com/kolypto/j2cli

**Comment by pdecat** [comment]
Alright, my bad, we are already using the replacement: https://github.com/claranet/dockerfiles/blob/master/terraform/Dockerfile#L15
