### ISSUE TITLE
[BUG] Detector fivexx_http_response - integration_aws-elasticsearch - Different metric names

### ISSUE THREAD

**Issue by nicolas-dsk-claranet** [claranet/terraform-signalfx-detectors#516]
**What is the module?**
[ntegration_aws-elasticsearch](https://github.com/claranet/terraform-signalfx-detectors/tree/master/modules/integration_aws-elasticsearch)

**What is the detector?**
fivexx_http_response

**Describe the bug**
The metric name used as a divisor within that detector is 'OpenSearchRequests'. However, as specified in the 
[AWS documentation](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-cloudwatchmetrics.html#managedomains-cloudwatchmetrics-cluster-metrics:~:text=OpenSearchRequests), the metric name was 'ElasticsearchRequests'. I suggest to use the same logic as in 'fourxx_http_response' detector, pass the divisor to '2xx'

**To Reproduce**
AWS env have a OpenSearch, still with the 'ElasticsearchRequests' name for example

**Comment by pdecat** [comment]
This is done intentionally and as recommended by [AWS documentation](url):

> 5xx alarms >= 10% of OpenSearchRequests

See also this [link](https://stackoverflow.com/questions/64235495/aws-elasticsearch-publishing-wrong-total-request-metric/72818868#72818868) that is mentioned [here](https://github.com/claranet/terraform-signalfx-detectors/blame/master/modules/integration_aws-elasticsearch/conf/02-4xx.yaml#L20).
